# Log
logging:
  level:
    org.springframework.web: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type: TRACE
  config: classpath:log4j2.yml

# Server
server:
  context-path: /isms
  port: 10080

# DataSource
isms:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost/isms?characterEncoding=UTF-8&serverTimezone=JST
    username: root
    password: root
    pool:
      max: 10
      min: 5
      initial: 5
      timeout:
        idle: 1800000
        max: -1
    transaction:
      timeout: 60
